// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Moira.ApiClient.Models.Api
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FeatureFlags : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The celebrationMode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CelebrationMode { get; set; }
#nullable restore
#else
        public string CelebrationMode { get; set; }
#endif
        /// <summary>The isPlottingAvailable property</summary>
        public bool? IsPlottingAvailable { get; set; }
        /// <summary>The isPlottingDefaultOn property</summary>
        public bool? IsPlottingDefaultOn { get; set; }
        /// <summary>The isReadonlyEnabled property</summary>
        public bool? IsReadonlyEnabled { get; set; }
        /// <summary>The isSubscriptionToAllTagsAvailable property</summary>
        public bool? IsSubscriptionToAllTagsAvailable { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Moira.ApiClient.Models.Api.FeatureFlags"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Moira.ApiClient.Models.Api.FeatureFlags CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Moira.ApiClient.Models.Api.FeatureFlags();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "celebrationMode", n => { CelebrationMode = n.GetStringValue(); } },
                { "isPlottingAvailable", n => { IsPlottingAvailable = n.GetBoolValue(); } },
                { "isPlottingDefaultOn", n => { IsPlottingDefaultOn = n.GetBoolValue(); } },
                { "isReadonlyEnabled", n => { IsReadonlyEnabled = n.GetBoolValue(); } },
                { "isSubscriptionToAllTagsAvailable", n => { IsSubscriptionToAllTagsAvailable = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("celebrationMode", CelebrationMode);
            writer.WriteBoolValue("isPlottingAvailable", IsPlottingAvailable);
            writer.WriteBoolValue("isPlottingDefaultOn", IsPlottingDefaultOn);
            writer.WriteBoolValue("isReadonlyEnabled", IsReadonlyEnabled);
            writer.WriteBoolValue("isSubscriptionToAllTagsAvailable", IsSubscriptionToAllTagsAvailable);
        }
    }
}
#pragma warning restore CS0618
