// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Moira.ApiClient.Event.All;
using Moira.ApiClient.Event.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Moira.ApiClient.Event
{
    /// <summary>
    /// Builds and executes requests for operations under \event
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::Moira.ApiClient.Event.All.AllRequestBuilder All
        {
            get => new global::Moira.ApiClient.Event.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Moira.ApiClient.event.item collection</summary>
        /// <param name="position">The ID of updated trigger</param>
        /// <returns>A <see cref="global::Moira.ApiClient.Event.Item.WithTriggerItemRequestBuilder"/></returns>
        public global::Moira.ApiClient.Event.Item.WithTriggerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("triggerID", position);
                return new global::Moira.ApiClient.Event.Item.WithTriggerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Moira.ApiClient.Event.EventRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/event", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Moira.ApiClient.Event.EventRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/event", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
