// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Moira.ApiClient.Models.Moira
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ScheduleDataDay_name
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Mon")]
        #pragma warning disable CS1591
        Mon,
        #pragma warning restore CS1591
        [EnumMember(Value = "Tue")]
        #pragma warning disable CS1591
        Tue,
        #pragma warning restore CS1591
        [EnumMember(Value = "Wed")]
        #pragma warning disable CS1591
        Wed,
        #pragma warning restore CS1591
        [EnumMember(Value = "Thu")]
        #pragma warning disable CS1591
        Thu,
        #pragma warning restore CS1591
        [EnumMember(Value = "Fri")]
        #pragma warning disable CS1591
        Fri,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sat")]
        #pragma warning disable CS1591
        Sat,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sun")]
        #pragma warning disable CS1591
        Sun,
        #pragma warning restore CS1591
    }
}
