// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Moira.ApiClient.Health.Notifier;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Moira.ApiClient.Health
{
    /// <summary>
    /// Builds and executes requests for operations under \health
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HealthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The notifier property</summary>
        public global::Moira.ApiClient.Health.Notifier.NotifierRequestBuilder Notifier
        {
            get => new global::Moira.ApiClient.Health.Notifier.NotifierRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Moira.ApiClient.Health.HealthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HealthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/health", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Moira.ApiClient.Health.HealthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HealthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/health", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
