// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Moira.Client.Models.Dto
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TreeOfProblems : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The syntax_ok property</summary>
        public bool? SyntaxOk { get; set; }
        /// <summary>The tree_of_problems property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Moira.Client.Models.Dto.ProblemOfTarget? TreeOfProblemsProp { get; set; }
#nullable restore
#else
        public global::Moira.Client.Models.Dto.ProblemOfTarget TreeOfProblemsProp { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Moira.Client.Models.Dto.TreeOfProblems"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Moira.Client.Models.Dto.TreeOfProblems CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Moira.Client.Models.Dto.TreeOfProblems();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "syntax_ok", n => { SyntaxOk = n.GetBoolValue(); } },
                { "tree_of_problems", n => { TreeOfProblemsProp = n.GetObjectValue<global::Moira.Client.Models.Dto.ProblemOfTarget>(global::Moira.Client.Models.Dto.ProblemOfTarget.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("syntax_ok", SyntaxOk);
            writer.WriteObjectValue<global::Moira.Client.Models.Dto.ProblemOfTarget>("tree_of_problems", TreeOfProblemsProp);
        }
    }
}
#pragma warning restore CS0618
