// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Moira.Client.Models.Moira
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NotificationEvent : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The contact_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>The event_message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Moira.Client.Models.Moira.EventInfo? EventMessage { get; set; }
#nullable restore
#else
        public global::Moira.Client.Models.Moira.EventInfo EventMessage { get; set; }
#endif
        /// <summary>The metric property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metric { get; set; }
#nullable restore
#else
        public string Metric { get; set; }
#endif
        /// <summary>The msg property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Msg { get; set; }
#nullable restore
#else
        public string Msg { get; set; }
#endif
        /// <summary>The old_state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OldState { get; set; }
#nullable restore
#else
        public string OldState { get; set; }
#endif
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The sub_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubId { get; set; }
#nullable restore
#else
        public string SubId { get; set; }
#endif
        /// <summary>The timestamp property</summary>
        public long? Timestamp { get; set; }
        /// <summary>The trigger_event property</summary>
        public bool? TriggerEvent { get; set; }
        /// <summary>The trigger_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerId { get; set; }
#nullable restore
#else
        public string TriggerId { get; set; }
#endif
        /// <summary>The value property</summary>
        public double? Value { get; set; }
        /// <summary>The values property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Moira.Client.Models.Moira.NotificationEvent_values? Values { get; set; }
#nullable restore
#else
        public global::Moira.Client.Models.Moira.NotificationEvent_values Values { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Moira.Client.Models.Moira.NotificationEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Moira.Client.Models.Moira.NotificationEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Moira.Client.Models.Moira.NotificationEvent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "event_message", n => { EventMessage = n.GetObjectValue<global::Moira.Client.Models.Moira.EventInfo>(global::Moira.Client.Models.Moira.EventInfo.CreateFromDiscriminatorValue); } },
                { "metric", n => { Metric = n.GetStringValue(); } },
                { "msg", n => { Msg = n.GetStringValue(); } },
                { "old_state", n => { OldState = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "sub_id", n => { SubId = n.GetStringValue(); } },
                { "timestamp", n => { Timestamp = n.GetLongValue(); } },
                { "trigger_event", n => { TriggerEvent = n.GetBoolValue(); } },
                { "trigger_id", n => { TriggerId = n.GetStringValue(); } },
                { "value", n => { Value = n.GetDoubleValue(); } },
                { "values", n => { Values = n.GetObjectValue<global::Moira.Client.Models.Moira.NotificationEvent_values>(global::Moira.Client.Models.Moira.NotificationEvent_values.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteObjectValue<global::Moira.Client.Models.Moira.EventInfo>("event_message", EventMessage);
            writer.WriteStringValue("metric", Metric);
            writer.WriteStringValue("msg", Msg);
            writer.WriteStringValue("old_state", OldState);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("sub_id", SubId);
            writer.WriteLongValue("timestamp", Timestamp);
            writer.WriteBoolValue("trigger_event", TriggerEvent);
            writer.WriteStringValue("trigger_id", TriggerId);
            writer.WriteDoubleValue("value", Value);
            writer.WriteObjectValue<global::Moira.Client.Models.Moira.NotificationEvent_values>("values", Values);
        }
    }
}
#pragma warning restore CS0618
