name: Build and push binaries to Nuget

on:
  push:
    branches: [ 'main' ]
  release:
    types: [ 'published' ]

  workflow_dispatch:
    inputs:
      url:
        description: 'url'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Echo
        run: echo ${{github.event.inputs.url}}